# Generated by Django 4.2.20 on 2025-04-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='sum',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=16),
        ),
    ]
