# Generated by Django 4.2.20 on 2025-04-10 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_order_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=100)),
                ('l_name', models.CharField(max_length=100)),
                ('m_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.EmailField(max_length=20)),
                ('country', models.EmailField(max_length=50)),
                ('street_address', models.EmailField(max_length=150)),
                ('apartment_address', models.EmailField(max_length=150)),
                ('town', models.EmailField(max_length=150)),
                ('post_code', models.IntegerField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='shop.order')),
            ],
            options={
                'db_table': 'billing_info',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('billinginfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shop.billinginfo')),
                ('other_notes', models.TextField()),
            ],
            options={
                'db_table': 'shipping_address',
                'ordering': ['-id'],
            },
            bases=('shop.billinginfo',),
        ),
    ]
